function createfigure_Map_Motor_Imagery_8x8(image, map, data, lims)
% this function is only meaningful in combination with the Chan_Layout_ER.jpg image
% this function overlays the channel positions on that image with colored
% circles
% INPUT
% image: image created based on Chan_Layout_ER.jpg 
% map:   a color map
% data:  data stored in the correct order in a matrix storing the channel
%        layout
% lims:  ploting limits
% pruned_chans: boolean vector - 0 if channel signal quality is bad, i.e.
%               will be pruned (output of qt-nirs, indices same as in
%               nirs-toolbox, i.e. via link table you can understand which
%               index belongs to which channel)

%
% Create figure
figure1 = figure;

% Create image
imshow(image);

% generate color vector based on values
dat = linspace(lims(1), lims(2), size(map,1));
for i = 1:length(data)
    if isnan(data(i)) 
        data(i) = 0;
    end
    idx_tmp = find(dat >= data(i));
    val = sort(dat(idx_tmp));
    [~, dat_idx(i)] = find(val(1) == dat);
end

% channel 1-1 - Premotor
if(data(1) == 0)
    annotation(figure1,'ellipse',...
    [0.425,0.65,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(1), :));
else
    
    annotation(figure1,'ellipse',...
        [0.425,0.65,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(1), :));
end

% channel 1-2 - SMA
if(data(2) == 0)
    annotation(figure1,'ellipse',...
    [0.49,0.65,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(2), :));
else
    
    annotation(figure1,'ellipse',...
        [0.49,0.65,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(2), :));
end

% channel 2-2 - Premotor
if(data(4) == 0)
    annotation(figure1,'ellipse',...
    [0.54,0.65,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(4), :));
else
    
    annotation(figure1,'ellipse',...
        [0.54,0.65,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(4), :));
end

% channel 3-1 - Premotor
if(data(6) == 0)
    annotation(figure1,'ellipse',...
    [0.395,0.625,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(6), :));
else
    
    annotation(figure1,'ellipse',...
    [0.395,0.625,0.025,0.025],...
    'LineWidth', 2,...
    'FaceColor', map(dat_idx(6), :));
end

% channel 1-4 - SMA
if(data(3) == 0)
    annotation(figure1,'ellipse',...
    [0.455,0.625,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(3), :));
else
    
    annotation(figure1,'ellipse',...
    [0.455,0.625,0.025,0.025],...
    'LineWidth', 2,...
        'FaceColor', map(dat_idx(3), :));
end

% channel 4-2 - SMA
if(data(10) == 0)
    annotation(figure1,'ellipse',...
    [0.515,0.625,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(10), :));
else
    
    annotation(figure1,'ellipse',...
    [0.515,0.625,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(10), :));
end

% channel 2-5 - Premotor
if(data(5) == 0)
    annotation(figure1,'ellipse',...
    [0.575,0.625,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(5), :));
else
    
    annotation(figure1,'ellipse',...
    [0.575,0.625,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(5), :));
end

% channel 3-3 - Left M1
if(data(7) == 0)
    annotation(figure1,'ellipse',...
    [0.36,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(7), :));
else
    
    annotation(figure1,'ellipse',...
    [0.36,0.6,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(7), :));
end

% channel 3-4 - Left M1
if(data(8) == 0)
    annotation(figure1,'ellipse',...
    [0.425,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(8), :));
else
    
    annotation(figure1,'ellipse',...
    [0.425,0.6,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(8), :));
end

% channel 4-4 - SMA
if(data(11) == 0)
    annotation(figure1,'ellipse',...
    [0.485,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(11), :));
else
    
    annotation(figure1,'ellipse',...
    [0.485,0.6,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(11), :));
end

% channel 4-5 - Right M1
if(data(12) == 0)
    annotation(figure1,'ellipse',...
    [0.55,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(12), :));
else
    
    annotation(figure1,'ellipse',...
    [0.55,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'FaceColor', map(dat_idx(12), :));
end

% channel 5-5 - Right M1
if(data(14) == 0)
    annotation(figure1,'ellipse',...
    [0.61,0.6,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(14), :));
else
    
    annotation(figure1,'ellipse',...
    [0.61,0.6,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(14), :));
end

% channel 3-6 - Left M1
if(data(9) == 0)
    annotation(figure1,'ellipse',...
    [0.39,0.555,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(9), :));
else
    
    annotation(figure1,'ellipse',...
    [0.39,0.555,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(9), :));
end

% channel 6-4 - SMA
if(data(15) == 0)
    annotation(figure1,'ellipse',...
    [0.455,0.56,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(15), :));
else
    
    annotation(figure1,'ellipse',...
    [0.455,0.56,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(15), :));
end

% channel 4-7 - SMA
if(data(13) == 0)
    annotation(figure1,'ellipse',...
    [0.52,0.555,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(13), :));
else
    
    annotation(figure1,'ellipse',...
    [0.52,0.555,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(13), :));
end

% channel 7-5 - Right M1
if(data(18) == 0)
    annotation(figure1,'ellipse',...
    [0.585,0.56,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(18), :));
else
    
    annotation(figure1,'ellipse',...
    [0.585,0.56,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(18), :));
end

% channel 6-6 - Left M1
if(data(16) == 0)
    annotation(figure1,'ellipse',...
        [0.42,0.52,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(16), :));
else
    
    annotation(figure1,'ellipse',...
        [0.42,0.52,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(16), :));
end

% channel 6-7 - SMA
if(data(17) == 0)
    annotation(figure1,'ellipse',...
    [0.49,0.52,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(17), :));
else
    
    annotation(figure1,'ellipse',...
    [0.49,0.52,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(17), :));
end

% channel 7-7 - Right M1
if(data(19) == 0)
    annotation(figure1,'ellipse',...
     [0.55,0.52,0.025,0.025],...
    'LineWidth', 2,...
    'Color', 'red',...
    'FaceColor', map(dat_idx(19), :));
else
    
    annotation(figure1,'ellipse',...
        [0.55,0.52,0.025,0.025],...
        'LineWidth', 2,...
        'FaceColor', map(dat_idx(19), :));
end