%% FEEDBACK VISUALISATION
function NFB_viz_BA9(xPosVector_mid, yPosVector_mid, xPosVector_left, yPosVector_left, xPosVector_right, yPosVector_right, isConvex, width, FBcolor, ...
    mainwin, framCol, white)
% function that displays polygons on tob-down view head (hard coded
% positions); left and right corresponds to information displayed
% on left and right hemisphere;
% INPUT
% xPosVector_left, yPosVector_left, xPosVector_right,
% yPosVector_right, isConvex:
% Polygon specific values for screen function 'FillPoly'
% width:    frame width for screen function 'FRamePoly'
% framCol:  frame color for screen function 'FRamePoly'
% FBcolor:  color for neurofeedback that colors the polygons
% mainwin:  window information generated by Psychtoolbox screen
% function
%Adapted for 3-polygons NFB on 20.3.25 by Murat

xoffset = (max(xPosVector_right)-min(xPosVector_right)) / 2; % ADDED by MURAT on 20.03.25
yoffset = (max(yPosVector_mid)-min(yPosVector_mid)) / 3; % ADDED by MURAT on 20.03.25

if white
    col = [255, 255, 255];
    %% middle
    
    % channel 1 of the streamed vector
    Screen('FillPoly',  mainwin, col,           [xPosVector_mid; yPosVector_mid-yoffset]', isConvex); % 1. von links oben;
    Screen('FramePoly', mainwin, framCol,       [xPosVector_mid; yPosVector_mid-yoffset]', width);
    
    %% left
    
    % channel 2 of the streamed vector, lower left
    Screen('FillPoly',  mainwin, col,           [xPosVector_left-xoffset; yPosVector_left+65]', isConvex);  % unten
    Screen('FramePoly', mainwin, framCol,       [xPosVector_left-xoffset; yPosVector_left+65]', width);
    
    %% right
    
    % channel 3 of the streamed vector, lower right
    Screen('FillPoly',  mainwin, col,           [xPosVector_right+xoffset; yPosVector_right+65]', isConvex); % unten
    Screen('FramePoly', mainwin, framCol,    	[xPosVector_right+xoffset; yPosVector_right+65]', width);
else
    %% middle
    
    % channel 1 of the streamed vector
    
    Screen('FillPoly',  mainwin, FBcolor(1, :),	 [xPosVector_mid; yPosVector_mid-yoffset]', isConvex); % 1. von links oben;
    Screen('FramePoly', mainwin, framCol,        [xPosVector_mid; yPosVector_mid-yoffset]', width);
    
    %% left
    
    % channel 2 of the streamed vector, lower left
    Screen('FillPoly',  mainwin, FBcolor(2, :),	[xPosVector_left-xoffset; yPosVector_left+65]', isConvex);  % 2. von links oben
    Screen('FramePoly', mainwin, framCol,       [xPosVector_left-xoffset; yPosVector_left+65]', width);

    %% right

    % channel 3 of the streamed vector, lower right
    Screen('FillPoly',  mainwin, FBcolor(3, :),	[xPosVector_right+xoffset; yPosVector_right+65]', isConvex); % unten
    Screen('FramePoly', mainwin, framCol,    	[xPosVector_right+xoffset; yPosVector_right+65]', width);
end

end